baseURL: https://notebook-7b2.pages.dev/
title: Mandarin Notebook
theme: PaperMod
locale: en-gb
hasCJKLanguage: true

pagination:
  pagerSize: 10

params:
  homeInfoParams:
    Title: "Mandarin Notebook"
    Content: >
      A personal blog about learning Mandarin and travelling in China.

      Based in Edinburgh, and studying Mandarin at the University of Strathclyde. This is where I practise writing, vocabulary, grammar notes, and short entries as I learn. I'll also post photos and stories from my study trip to Capital Normal University in Beijing.
  socialIcons:
    - name: "github"
      url: "https://github.com/dale-mcintyre"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/daleamcintyre"
    - name: "instagram"
      url: "https://www.instagram.com/dale_wine"
    - name: "wechat"
      url: "https://weixin.qq.com/"
    - name: "lastfm"
      url: "https://www.last.fm/user/dalemcintyre"
  defaultTheme: auto

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 20