baseURL = 'https://notebook-7b2.pages.dev/'
locale = 'en-gb'
title = 'Mandarin Notebook'
theme = "console"
summaryLength = 20

[params]
  description = "A personal blog about learning Mandarin and travelling in China"
navlinks = [
    { name = "Archive", url = "/posts/" },
    { name = "Photos", url = "/photos/" },
    { name = "About", url = "/about/" }
  ]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true